### PR TITLE
Adds requirements to readme

### PR DESCRIPTION
**Pull request by henriquelbsouza**

### CODE REVIEW

**Comment by pandafy** [comment]
@henriquelbsouza can you add indentation on install commands in requirements?

**Comment by henriquelbsouza** [comment]
> @henriquelbsouza can you add indentation on install commands in requirements?

Sure thing, it is done :)

**Comment by pandafy** [comment]
Not exactly what I wanted. Check out this [link](https://stackoverflow.com/questions/6046263/how-to-indent-a-few-lines-in-markdown-markup)

**Comment by henriquelbsouza** [comment]
Is it better?

**Comment by pandafy** [comment]
Not actually, I don't want installation commands on next line. I want the whole content of requirements section to be indented. Like

## Requirements
&nbsp;&nbsp;&nbsp;&nbsp; OS : `installation command`

**Comment by henriquelbsouza** [comment]
Done

**Comment by pandafy** [comment]
Excellent! @henriquelbsouza we'll prefer a one commit pull request here, if you can stash all your commits to one or send a new pull request containing on this change, I'll merge it right away. Will you consider this?

**Comment by henriquelbsouza** [comment]
Done :)

**Pull request merged**
